version: '3'

networks:
  cursosnetwork:
    driver: bridge


services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - cursosnetwork
    environment:
        MYSQL_ROOT_PASSWORD: rootpw
        MYSQL_DATABASE: chairdb
        MYSQL_USER: root
        MYSQL_PASSWORD: toor
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
      - cursosnetwork
    ports:
      - 8081:8080

volumes:
  db-data:
